"""
Cookie conversion utilities.
"""

from pathlib import Path
from typing import Dict, List, Union


def playwright_to_netscape(cookies: List[Dict[str, Union[str, int, bool]]]) -> str:
    """
    Convert Playwright cookies to Netscape HTTP Cookie File format.
    
    Format:
    domain  flag  path  secure  expiration  name  value
    
    Args:
        cookies: List of cookie dictionaries from Playwright
        
    Returns:
        String content of the Netscape cookie file
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by DawnChat.",
        "# http://curl.haxx.se/rfc/cookie_spec.html",
        ""
    ]
    
    for cookie in cookies:
        domain_value = cookie.get("domain", "")
        domain = domain_value if isinstance(domain_value, str) else str(domain_value)
        # flag: TRUE if domain starts with .
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure", False) else "FALSE"
        
        # expiration
        expires = cookie.get("expires", -1)
        if expires == -1:
            # Session cookie, use 0 or a far future date?
            # Netscape format usually uses 0 for session cookies, 
            # but some tools might ignore them. 
            # Let's keep it as 0.
            expires = 0
        else:
            expires = int(expires)
            
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
        
    return "\n".join(lines)

def save_cookies_to_netscape(cookies: List[Dict], path: Path) -> None:
    """
    Save Playwright cookies to a file in Netscape format.
    
    Args:
        cookies: List of cookie dictionaries
        path: Output file path
    """
    content = playwright_to_netscape(cookies)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
